# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Supply chain project CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        mkdir FastAPI
        # sudo cp config/http_ca.crt /etc/ssl/certs
        # chown root:root /etc/ssl/certs/http_ca.crt
        python -m pip install --upgrade pip
        pip install "fastapi[all]"
        python -m pip install --upgrade pip
        pip install "uvicorn[standard]"
        python -m pip install --upgrade pip
        python -m pip install elasticsearch
        python -m pip install "elasticsearch[async]"
        python -m pip install --upgrade pip
        pip install python-dotenv
        pip install pandas
        pip install beautifulsoup4
        pip install numpy
        pip install seaborn
        python -m pip install --upgrade pip
        python -m pip install -U pip
        python -m pip install -U matplotlib
        python -m pip install -U nltk
        python -m pip install --upgrade pip
        python -m pip install -U scikit-learn
        python -m pip install textblob
        python -m pip install afinn
        python -m pip install vaderSentiment
        python -m pip install pytest
        cd /FastAPI/server
    - name: Test api
      run: |
        pytest